### ISSUE TITLE
java.lang.NoSuchFieldError: BACK

### ISSUE THREAD

**Issue by xcocean** [AlmasB/FXGL#1106]
Basic presentation
When I click the screen with the mouse, the following exception appears
jdk11 and javafx 11 and fxgl 11.17
![image](https://user-images.githubusercontent.com/45192548/134933099-e126c9cf-b56d-4ac4-b87d-87aded533866.png)

```java
Message:  BACK
Type:  NoSuchFieldError
Method:  MouseTrigger$Companion$WhenMappings.<clinit>()
Line:  Triggers.kt

java.lang.NoSuchFieldError: BACK
	at com.almasb.fxgl.input.MouseTrigger$Companion$WhenMappings.<clinit>(Triggers.kt)
	at com.almasb.fxgl.input.MouseTrigger$Companion.buttonToString(Triggers.kt:130)
	at com.almasb.fxgl.input.MouseTrigger.<init>(Triggers.kt:143)
	at com.almasb.fxgl.input.MouseTrigger.<init>(Triggers.kt:112)
	at com.almasb.fxgl.input.Input.handlePressed(Input.kt:326)
	at com.almasb.fxgl.input.Input.onMouseEvent(Input.kt:312)
	at com.almasb.fxgl.input.Input.onMouseEvent(Input.kt:301)
	at com.almasb.fxgl.app.PrimaryStageWindow$2.invoke(MainWindow.kt:293)
	at com.almasb.fxgl.app.PrimaryStageWindow$2.invoke(MainWindow.kt:292)
	at com.almasb.fxgl.app.MainWindow.addMouseHandler$lambda-2(MainWindow.kt:230)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xcocean** [comment]
Start have a warning

```
23:00:32.385 [JavaFX Application Thread] INFO  Engine               - FXGL-11.17 (16.07.2021 15.46) on WINDOWS (J:11.0.12 FX:11)
23:00:32.386 [JavaFX Application Thread] INFO  Engine               - Source code and latest versions at: https://github.com/AlmasB/FXGL
23:00:32.386 [JavaFX Application Thread] INFO  Engine               -              Join the FXGL chat at: https://gitter.im/AlmasB/FXGL
23:00:33.054 [FXGL Background Thread 1 ] WARN  SystemBundleService  - Failed to load: java.io.FileNotFoundException: C:\Users\Administrator\Desktop\project\javaFx\sz\system\fxgl.bundle (系统找不到指定的文件。)
23:00:33.072 [FXGL Background Thread 1 ] INFO  FXGLApplication      - FXGL initialization took: 0.359 sec
23:00:33.121 [FXGL Background Thread 1 ] INFO  FXGLApplication      - Game initialization took: 0.001 sec
23:00:36.043 [JavaFX Application Thread] FATAL FXGLApplication      - Uncaught Exception:
java.lang.NoSuchFieldError: BACK
	at com.almasb.fxgl.input.MouseTrigger$Companion$WhenMappings.<clinit>(Triggers.kt)
	at com.almasb.fxgl.input.MouseTrigger$Companion.buttonToString(Triggers.kt:130)
	at com.almasb.fxgl.input.MouseTrigger.<init>(Triggers.kt:143)
```

**Comment by xcocean** [comment]
sorry ，I found the reason。
because I added javafx dependency
```java
    <dependencies>
       <!-- <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>11</version>
        </dependency>-->

        <!--游戏引擎-->
        <dependency>
            <groupId>com.github.almasb</groupId>
            <artifactId>fxgl</artifactId>
            <version>11.17</version>
        </dependency>
    </dependencies>
```

![image](https://user-images.githubusercontent.com/45192548/134938702-ac52179c-3fb2-433f-ac7c-0d0a85345722.png)
