### ISSUE TITLE
PhysicsComponent crash when using PhysicsComponent.reposition(Point2D)

### ISSUE THREAD

**Issue by gmolinsm** [AlmasB/FXGL#690]
I'm trying to make my character entity reposition itself after colliding with another entity.
For some reason I keep getting this crash error message:

java.lang.IllegalStateException: Physics world is locked during time step
	at com.almasb.fxgl.physics.box2d.dynamics.World.assertNotLocked(World.java:1412)
	at com.almasb.fxgl.physics.box2d.dynamics.Body.setTransform(Body.java:287)
	at com.almasb.fxgl.physics.PhysicsComponent.reposition(PhysicsComponent.java:422)
	at sample.Main$5.onCollisionBegin(Main.java:73)
	at com.almasb.fxgl.physics.CollisionPair.collisionBegin(CollisionPair.java:44)
	at com.almasb.fxgl.physics.PhysicsWorld.beginContact(PhysicsWorld.java:324)
	at com.almasb.fxgl.physics.box2d.dynamics.contacts.Contact.update(Contact.java:277)
	at com.almasb.fxgl.physics.box2d.dynamics.World.solveTOI(World.java:629)
	at com.almasb.fxgl.physics.box2d.dynamics.World.step(World.java:314)
	at com.almasb.fxgl.physics.PhysicsWorld.onUpdate(PhysicsWorld.java:235)
	at com.almasb.fxgl.app.PlayState.step(AppStates.kt:245)
	at com.almasb.fxgl.app.PlayState.onUpdate(AppStates.kt:240)
	at com.almasb.fxgl.app.State.update(State.java:73)
	at com.almasb.fxgl.app.AppStateMachine.onUpdate(AppStateMachine.java:100)
	at com.almasb.fxgl.app.FXGL.loop(FXGL.kt:356)
	at com.almasb.fxgl.app.FXGL.access$loop(FXGL.kt:54)
	at com.almasb.fxgl.app.FXGL$loop$1.accept(FXGL.kt:78)
	at com.almasb.fxgl.app.FXGL$loop$1.accept(FXGL.kt:54)
	at com.almasb.fxgl.app.LoopRunner.frame(LoopRunner.kt:88)
	at com.almasb.fxgl.app.LoopRunner.access$frame(LoopRunner.kt:19)
	at com.almasb.fxgl.app.LoopRunner$impl$2$1.handle(LoopRunner.kt:39)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$485(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

Any help would be appreciated!

**Comment by AlmasB** [comment]
@gmolinsm Hi, based on the error message (`Physics world is locked during time step`) and what you've described, I suspect that during collision detection and notification, the physics world is locked for modification. This means no entity with `PhysicsComponent` can change its physics properties, e.g. position, which is expected behaviour.

I think the workaround here is you capture the fact that collision occurred -- a simple boolean flag should do and handle later. For example, in `onUpdate()` of the `App` class:

```
if (flag) {
    reposition()
    flag = false
}
```

See if something like this solves the issue?

**Comment by gmolinsm** [comment]
Hi @AlmasB, thank you for the quick response. 
I was unaware of this and I didn't implement the onUpdate() method, now it works :)
