### ISSUE TITLE
Stage.title : A bound value cannot be set.

### ISSUE THREAD

**Issue by bryaan** [AlmasB/FXGL#724]
I'm trying to launch the simple java example from a Kotlin TornadoFX button action.  It shows the screen initially but then quickly fails with "Stage.title : A bound value cannot be set."

```
            button("My Game") {
                action {
                    GameApplication.customLaunch(MyGame(), currentStage)
                }
            }
```

```
public class MyGame extends GameApplication {

    @Override
    protected void initSettings(GameSettings settings) {
        settings.setWidth(800);
        settings.setHeight(600);
        settings.setTitle("BasicGameSample");
    }

    @Override
    protected void initGame() {
        FXGL.entityBuilder()
                .at(150, 150)
                .view(new Rectangle(40, 40, Color.BLUE))
                .buildAndAttach();
    }
}
```
```

java.lang.RuntimeException: Stage.title : A bound value cannot be set.
	at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:141)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
	at javafx.graphics/javafx.stage.Stage.setTitle(Stage.java:735)
	at com.almasb.fxgl.app.MainWindow.initStage(MainWindow.kt:174)
	at com.almasb.fxgl.app.MainWindow.<init>(MainWindow.kt:79)
	at com.almasb.fxgl.app.Engine.initAndShowMainWindow(Engine.kt:232)
	at com.almasb.fxgl.app.Engine.startLoop(Engine.kt:177)
```

**Comment by bryaan** [comment]
Simple as:

                    val stage = Stage()
                    GameApplication.customLaunch(KotlinGameApp(), stage)
