### ISSUE TITLE
Add option to disable writing to file system

### ISSUE THREAD

**Issue by fuzzysearch404** [AlmasB/FXGL#847]
**A clear and concise description of what the feature is.**
When the application is placed in a directory, where FXGL is unable to create/write files and/or directories, the FXGL application might not start, or the application runs with errors.

**Describe the solution you'd like**
New FXGL setting/settings, that would allow disabling FXGL file writing and directory creation to file system.

**Additional context (optional)**
Case scenario - if the FXGL application is packed in an installer, where during installation, user can select installation folder, and the user selects folder with elevated privileges, e. g. on Windows `Program files`, after the installation, the program does not run, because it could not create some directories and files.

**Comment by AlmasB** [comment]
@fuzzysearch404 this is now building..

To get the latest build, you can use this:
```
<dependencies>
    <dependency>
        <groupId>com.github.almasb</groupId>
        <artifactId>fxgl</artifactId>
        <version>dev-SNAPSHOT</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

You can disable any FS write calls by setting `settings.setFileSystemWriteAllowed(false);`. Please check this works for the above use case before closing.

**Comment by fuzzysearch404** [comment]
@AlmasB Seems like `isFileSystemWriteAllowed` is missing.
```
Message:  Cannot inject @Inject(isFileSystemWriteAllowed). No value present for isFileSystemWriteAllowed
Type:  IllegalArgumentException
Method:  Engine.injectDependenciesIntoService()
Line:  Engine.kt:100

java.lang.IllegalArgumentException: Cannot inject @Inject(isFileSystemWriteAllowed). No value present for isFileSystemWriteAllowed
	at com.almasb.fxgl.app.Engine.injectDependenciesIntoService(Engine.kt:100)
	at com.almasb.fxgl.app.Engine.initServices(Engine.kt:77)
	at com.almasb.fxgl.app.FXGLApplication$start$task$1.run(FXGLApplication.kt:117)
	at com.almasb.fxgl.core.concurrent.IOTask.lambda$ofVoid$5(IOTask.java:138)
	at com.almasb.fxgl.core.concurrent.IOTask$2.onExecute(IOTask.java:151)
	at com.almasb.fxgl.core.concurrent.IOTask$1.call(IOTask.java:107)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by AlmasB** [comment]
Odd, I can't reproduce this for some reason. Could you provide the full build number? It should be `FXGL-dev-SNAPSHOT (14.07.2020 13.23)`

Also, are you running this from an IDE or the no-access folder?

**Comment by fuzzysearch404** [comment]
@AlmasB Oops, seems like my IDE messed something up, when switching dependencies.
Now FXGL runs just fine, but when placed in no-access folder there is this logging exception:
```
Error during launch:
java.nio.file.AccessDeniedException: logs
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:506)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at com.almasb.fxgl.logging.FileOutput.getOrCreateLogDir(FileOutput.kt:46)
        at com.almasb.fxgl.logging.FileOutput.<init>(FileOutput.kt:27)
        at com.almasb.fxgl.logging.FileOutput.<init>(FileOutput.kt:22)
        at com.almasb.fxgl.logging.FileOutput.<init>(FileOutput.kt)
        at com.almasb.fxgl.app.GameApplication.initLogger(GameApplication.java:133)
        at com.almasb.fxgl.app.GameApplication.launch(GameApplication.java:85)
        at com.almasb.fxgl.app.GameApplication.launch(GameApplication.java:53)
        at game.Game.main(Game.java:67)
Application will now exit
```

**Comment by AlmasB** [comment]
Is this with FS write set to false?

initLogger 133 is, so it shouldn't get inside the if ... hmmm
```
        if (settings.isFileSystemWriteAllowed() && settings.isDesktop() && !settings.isExperimentalNative()) {
            Logger.addOutput(new FileOutput("FXGL"), LoggerLevel.DEBUG);
        }
```

**Comment by fuzzysearch404** [comment]
Yes. I did set it to false.
I recompiled everything again, and I can't reproduce that again. Now everything is working fine in no-access directories.
Thank You for implementing this feature so quickly :)
