### ISSUE TITLE
Tilesheet and Tiled map of non-uniform dimensions fail or render unexpected results

### ISSUE THREAD

**Issue by adambocco** [AlmasB/FXGL#985]
**Describe the bug**
When creating a map in Tiled for tiles of size 32x16 and using a tilesheet defined with 16x32 tiles there are some cases in which tiles placed partially out of bounds throw an error. For example, placing an over-sized tiled at the top-left does not throw an error.

![image](https://user-images.githubusercontent.com/54448507/110243465-77303700-7f28-11eb-8e2d-b32c22078d94.png)

with tile:
![image](https://user-images.githubusercontent.com/54448507/110243494-a0e95e00-7f28-11eb-8ac5-b68c2cab8e8d.png)

FXGL will render this:
![image](https://user-images.githubusercontent.com/54448507/110243777-d0e53100-7f29-11eb-9cff-33391af7d566.png)

However, adding a tile at the bottom makes the total height of the image larger than the map's defined height.
![image](https://user-images.githubusercontent.com/54448507/110243535-cbd3b200-7f28-11eb-89e8-520e52d9bb3e.png)

and it throws this error:
```
ava.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 32832 out of bounds for byte[32768]
	at java.base/java.lang.System.arraycopy(Native Method)
	at javafx.graphics/com.sun.javafx.image.impl.BaseByteToByteConverter$ByteAnyToSameConverter.doConvert(BaseByteToByteConverter.java:176)
	at javafx.graphics/com.sun.javafx.image.impl.BaseByteToByteConverter.convert(BaseByteToByteConverter.java:99)
	at javafx.graphics/com.sun.javafx.image.impl.BaseByteToByteConverter$ByteAnyToSameConverter.convert(BaseByteToByteConverter.java:165)
	at javafx.graphics/com.sun.prism.Image$BaseAccessor.getPixels(Image.java:1031)
	at javafx.graphics/com.sun.prism.Image.getPixels(Image.java:697)
	at javafx.graphics/javafx.scene.image.Image$2.getPixels(Image.java:1217)
	at javafx.graphics/com.sun.prism.Image$ByteAccess.setPixels(Image.java:1123)
	at javafx.graphics/com.sun.prism.Image.setPixels(Image.java:754)
	at javafx.graphics/javafx.scene.image.WritableImage$2.setPixels(WritableImage.java:268)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.level.tiled.TilesetLoader.loadView(TilesetLoader.kt:137)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.level.tiled.TMXLevelLoader.createTileLayerEntities(TMXLevelLoader.kt:86)
	at com.almasb.fxgl.entity/com.almasb.fxgl.entity.level.tiled.TMXLevelLoader.load(TMXLevelLoader.kt:51)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.services.FXGLAssetLoaderService.loadLevel(FXGLAssetLoaderService.kt:442)
	at com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL$Companion.setLevelFromMap(FXGL.kt:532)
	at com.almasb.fxgl.all/com.almasb.fxgl.dsl.FXGL.setLevelFromMap(FXGL.kt)
	at samples.main/sandbox.TiledMapSample.initGame(TiledMapSample.java:53)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.FXGLApplication$InitAppTask.initGame(FXGLApplication.kt:372)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.FXGLApplication$InitAppTask.call(FXGLApplication.kt:352)
	at com.almasb.fxgl.all/com.almasb.fxgl.app.FXGLApplication$InitAppTask.call(FXGLApplication.kt:344)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
Likewise, trying to load a map for 16x32 tiles and placing 32x16 tiles will result in this:
![image](https://user-images.githubusercontent.com/54448507/110243827-0f7aeb80-7f2a-11eb-89a8-3fa11a2ebbbd.png)
![image](https://user-images.githubusercontent.com/54448507/110243835-199cea00-7f2a-11eb-99ff-319282074e95.png)
![image](https://user-images.githubusercontent.com/54448507/110243847-23bee880-7f2a-11eb-91b3-dd093653fbf4.png)

Yet adding another tile, will not throw an error and will overwrite part of the left tile placed with the overflow of the right placed one:
 
![image](https://user-images.githubusercontent.com/54448507/110243934-87491600-7f2a-11eb-8db8-465625285205.png)
![image](https://user-images.githubusercontent.com/54448507/110243942-8d3ef700-7f2a-11eb-8229-f431b3198515.png)

Lastly, keeping all tiles in bounds but with the same dimensions as the above example merges the tile images where there is overflow:
![image](https://user-images.githubusercontent.com/54448507/110244203-9aa8b100-7f2b-11eb-9daf-509da4221b2a.png)

Whereas FXGL will overwrite the overflow of the first tile's image with the next parsed tile:
![image](https://user-images.githubusercontent.com/54448507/110244230-b6ac5280-7f2b-11eb-9f7a-a0f735763b27.png)

**To Reproduce**
1. Create a Tiled map and place tiles of varying dimensions which will overflow the map's defined tilespace. Ex) A map of 16x16 tiles and a tilesheet of 16x32 tiles.
2. Load the map in a new FXGL application using `setLevelFromMap('map.tmx')`
3. Run the application to see how FXGL handles overflowing tiles or witness an error similar to the one above.

**Expected behavior**
I would expect that placing a tile outside of the bounds of the map to be ignored/cropped. As for tiles overflowing into other tilespace within the bounds of the map, I would expect that FXGL overwrite the overflowing image as it does in Tiled, by overlaying the current tile's image and whatever image overflows into it.

However, it may be simpler to say that no tile can overflow its bounds. For example, a map of 16x16 tile-spaces using a 32x16 would only ever render the first 16x16 pixels and crop off the rest. But this would cause the possible creation of maps in Tiled that look entirely different from how FXGL chooses to render.

**Comment by adambocco** [comment]
@AlmasB 
I'm glad to work on this after determining what the expected behavior should be. However, if you have other open issues that are more pressing, just mention me or let me know.

Thanks

**Comment by AlmasB** [comment]
I will need to think about the expected behavior for these cases. Meanwhile, I'll mention you in a few other issues, which may be of interest.
